import type { ScheduleSubmission } from "../types/submission";

export const mockSubmissions: ScheduleSubmission[] = [
  {
    student: {
      id: "student-001",
      name: "Alice Johnson",
      location: "hsl"
    },
    schedule: [
      { day: "Mon", time: "08:00", type: "available" },
      { day: "Mon", time: "08:30", type: "available" },
      { day: "Mon", time: "09:00", type: "class" },
      { day: "Mon", time: "09:30", type: "class" },
      { day: "Mon", time: "10:00", type: "available" },
      { day: "Mon", time: "10:30", type: "available" },
      { day: "Mon", time: "11:00", type: "preferred" },
      { day: "Mon", time: "14:00", type: "available" },
      { day: "Mon", time: "14:30", type: "available" },
      { day: "Tue", time: "08:00", type: "available" },
      { day: "Tue", time: "08:30", type: "notAvailable" },
      { day: "Tue", time: "09:00", type: "notAvailable" },
      { day: "Tue", time: "10:00", type: "available" },
      { day: "Tue", time: "10:30", type: "available" },
      { day: "Tue", time: "11:00", type: "preferred" },
      { day: "Wed", time: "08:00", type: "available" },
      { day: "Wed", time: "09:00", type: "class" },
      { day: "Wed", time: "09:30", type: "class" },
      { day: "Wed", time: "10:00", type: "available" },
      { day: "Wed", time: "14:00", type: "preferred" },
      { day: "Thu", time: "08:00", type: "available" },
      { day: "Thu", time: "10:00", type: "available" },
      { day: "Thu", time: "10:30", type: "available" },
      { day: "Thu", time: "11:00", type: "available" },
      { day: "Thu", time: "14:00", type: "preferred" },
      { day: "Fri", time: "08:00", type: "available" },
      { day: "Fri", time: "08:30", type: "available" },
      { day: "Fri", time: "10:00", type: "notAvailable" },
    ],
    notes: "Prefer afternoon shifts on Monday and Wednesday",
    submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    student: {
      id: "student-002",
      name: "Bob Smith",
      location: "hsl"
    },
    schedule: [
      { day: "Mon", time: "08:00", type: "notAvailable" },
      { day: "Mon", time: "08:30", type: "notAvailable" },
      { day: "Mon", time: "09:00", type: "available" },
      { day: "Mon", time: "10:00", type: "available" },
      { day: "Mon", time: "10:30", type: "available" },
      { day: "Mon", time: "11:00", type: "available" },
      { day: "Mon", time: "14:00", type: "preferred" },
      { day: "Tue", time: "08:00", type: "available" },
      { day: "Tue", time: "09:00", type: "class" },
      { day: "Tue", time: "09:30", type: "class" },
      { day: "Tue", time: "10:00", type: "available" },
      { day: "Tue", time: "14:00", type: "available" },
      { day: "Tue", time: "14:30", type: "preferred" },
      { day: "Wed", time: "08:00", type: "available" },
      { day: "Wed", time: "08:30", type: "available" },
      { day: "Wed", time: "10:00", type: "available" },
      { day: "Wed", time: "10:30", type: "available" },
      { day: "Wed", time: "14:00", type: "available" },
      { day: "Thu", time: "09:00", type: "class" },
      { day: "Thu", time: "09:30", type: "class" },
      { day: "Thu", time: "10:00", type: "available" },
      { day: "Thu", time: "14:00", type: "available" },
      { day: "Fri", time: "08:00", type: "notAvailable" },
      { day: "Fri", time: "08:30", type: "available" },
      { day: "Fri", time: "10:00", type: "available" },
    ],
    notes: "Available most mornings",
    submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    student: {
      id: "student-003",
      name: "Carol White",
      location: "hsl"
    },
    schedule: [
      { day: "Mon", time: "08:00", type: "available" },
      { day: "Mon", time: "08:30", type: "available" },
      { day: "Mon", time: "09:00", type: "available" },
      { day: "Mon", time: "10:00", type: "preferred" },
      { day: "Mon", time: "10:30", type: "preferred" },
      { day: "Mon", time: "14:00", type: "available" },
      { day: "Tue", time: "08:00", type: "notAvailable" },
      { day: "Tue", time: "09:00", type: "available" },
      { day: "Tue", time: "10:00", type: "available" },
      { day: "Tue", time: "10:30", type: "available" },
      { day: "Tue", time: "14:00", type: "available" },
      { day: "Wed", time: "08:00", type: "available" },
      { day: "Wed", time: "09:00", type: "class" },
      { day: "Wed", time: "09:30", type: "class" },
      { day: "Wed", time: "10:00", type: "available" },
      { day: "Wed", time: "14:00", type: "preferred" },
      { day: "Thu", time: "08:00", type: "available" },
      { day: "Thu", time: "08:30", type: "available" },
      { day: "Thu", time: "09:00", type: "available" },
      { day: "Thu", time: "10:00", type: "available" },
      { day: "Fri", time: "08:00", type: "available" },
      { day: "Fri", time: "08:30", type: "available" },
      { day: "Fri", time: "10:00", type: "available" },
    ],
    notes: "Strong availability early in week",
    submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    student: {
      id: "student-004",
      name: "David Brown",
      location: "hsl"
    },
    schedule: [
      { day: "Mon", time: "08:00", type: "available" },
      { day: "Mon", time: "14:00", type: "available" },
      { day: "Mon", time: "14:30", type: "available" },
      { day: "Mon", time: "15:00", type: "preferred" },
      { day: "Tue", time: "08:00", type: "available" },
      { day: "Tue", time: "10:00", type: "available" },
      { day: "Tue", time: "14:00", type: "available" },
      { day: "Tue", time: "14:30", type: "available" },
      { day: "Wed", time: "08:00", type: "notAvailable" },
      { day: "Wed", time: "09:00", type: "class" },
      { day: "Wed", time: "09:30", type: "class" },
      { day: "Wed", time: "10:00", type: "available" },
      { day: "Wed", time: "14:00", type: "available" },
      { day: "Thu", time: "08:00", type: "available" },
      { day: "Thu", time: "08:30", type: "available" },
      { day: "Thu", time: "14:00", type: "preferred" },
      { day: "Thu", time: "14:30", type: "preferred" },
      { day: "Fri", time: "08:00", type: "notAvailable" },
      { day: "Fri", time: "08:30", type: "available" },
      { day: "Fri", time: "10:00", type: "available" },
    ],
    notes: "Limited availability due to classes",
    submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockManagerPassword = "demo-password";
